-- ✅ Top 10 best-selling products by quantity
-- Helps identify most popular products based on sales volume
SELECT 
  p.product_name,
  SUM(s.quantity) AS total_quantity_sold
FROM `intro-to-bq-465716.wisdom_pets.sales` s
JOIN `intro-to-bq-465716.wisdom_pets.products` p
  ON s.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 10;

-- --------------------------------------------------

-- ✅ Revenue generated by each product category
-- Useful for understanding category-wise financial contribution
SELECT 
  p.category_name,
  ROUND(SUM(s.total_amount), 0) AS category_revenue
FROM `intro-to-bq-465716.wisdom_pets.sales` s
JOIN `intro-to-bq-465716.wisdom_pets.products` p 
  ON s.product_id = p.product_id
GROUP BY p.category_name
ORDER BY category_revenue DESC;

-- --------------------------------------------------

-- ✅ Analyzing product ratings vs. sales
-- Reveals if highly rated products align with sales performance
SELECT 
  p.product_name,
  p.rating,
  ROUND(SUM(s.total_amount), 0) AS total_sales
FROM `intro-to-bq-465716.wisdom_pets.sales` s
JOIN `intro-to-bq-465716.wisdom_pets.products` p 
  ON s.product_id = p.product_id
WHERE p.rating IS NOT NULL
GROUP BY p.product_name, p.rating
ORDER BY total_sales DESC;

-- --------------------------------------------------

-- ✅ Compare average selling price per unit vs. listed price
-- Identifies discounts or overpricing based on actual transaction data
SELECT 
  p.product_name,
  ROUND(SUM(s.total_amount) / NULLIF(SUM(s.quantity), 0), 2) AS avg_selling_price,
  p.retail_price AS listed_price,
  ROUND(p.retail_price - ROUND(SUM(s.total_amount) / NULLIF(SUM(s.quantity), 0), 2), 2) AS price_diff
FROM `intro-to-bq-465716.wisdom_pets.sales` s
JOIN `intro-to-bq-465716.wisdom_pets.products` p 
  ON s.product_id = p.product_id
GROUP BY p.product_name, p.retail_price
ORDER BY price_diff DESC;

-- --------------------------------------------------

-- ✅ Breakdown of transaction types (Purchase vs Return)
-- Allows analysis of return rate and sales distribution
SELECT 
  transaction_type,
  COUNT(transaction_id) AS total_transactions,
  ROUND(SUM(total_amount), 2) AS total_value
FROM `intro-to-bq-465716.wisdom_pets.sales`
GROUP BY transaction_type
ORDER BY total_value DESC;
